### ISSUE TITLE
Hash generate on LoginController

### ISSUE THREAD

**Issue by lcloss** [devsavage/slim-3-authentication#4]
Hi @devsavage , first of all congratulations for your project. It helped me a lot to understand some issues that I could not handle with Slim3.

I believe that in LoginController, at lines 47, 48, the code must be:

```
$rememberIdentifier = $this->hash->generate(128);
$rememberToken = $this->hash->generate(128);

```
Instead of:

```
$rememberIdentifier = $this->hash->generateString(128);
$rememberToken = $this->hash->generateString(128);

```

I will continue to look at the code because I would like to understand how the password remember cookies work.

Thanks.

**Comment by devsavage** [comment]
Thank you @lcloss for finding this. I went ahead and made the changes! A quick overview of how the remember system works is we create an identifier and a token. The identifier stays the same in the database and the cookie but the token is plain in the cookie and hashed in the database. Then we use middleware to every time the page is loaded to verify if a cookie is present and is valid.
