### ISSUE TITLE
Violin issue

### ISSUE THREAD

**Issue by Tzhf** [devsavage/slim-3-authentication#5]
New issue appeared recently while submitting form (empty field)
Warning: count(): Parameter must be an array or an object that implements Countable in /home/tzhf/Projects/Hebergements-Slim/vendor/alexgarrett/violin/src/Support/MessageBag.php on line 55

**Comment by Tzhf** [comment]
Issue due to PHP 7.2, switched to 7.0, everything's ok.

**Comment by abmcr** [comment]
I have fixed in my php 7.2 environement as

`public function first($key = null)
    {
        if ($this->get($key) && count($this->get($key)) == 1) {
            $messages = is_null($key) ? $this->all() : $this->get($key);
            return ((count($messages) > 0) && (is_array($messages))) ? $messages[0] : null;
        } else {
            return null;
        }
    }`
