### ISSUE TITLE
Uncaught Error: Class 'Dotenv\Environment\DotenvFactory' not found

### ISSUE THREAD

**Issue by ingenuityon** [devsavage/slim-3-authentication#6]
I have no idea why this keeps coming up, I've tried everything I can find from others who've had this issue (albeit in other packages).  The issue triggers in: vendor/illuminate/support/helpers.php:646

Stack trace:
#0 /Applications/MAMP/htdocs/auth/config/app.php(4): env('APP_ENV', 'development')
#1 /Applications/MAMP/htdocs/auth/vendor/hassankhan/config/src/FileParser/Php.php(31): require('/Applications/M...')
#2 /Applications/MAMP/htdocs/auth/vendor/hassankhan/config/src/Config.php(69): Noodlehaus\FileParser\Php->parse('/Applications/M...')
#3 /Applications/MAMP/htdocs/auth/bootstrap/app.php(28): Noodlehaus\Config->__construct('/Applications/M...')
#4 /Applications/MAMP/htdocs/auth/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#5 /Applications/MAMP/htdocs/auth/bootstrap/container.php(113): Pimple\Container->offsetGet('config')
#6 /Applications/MAMP/htdocs/auth/vendor/pimple/pimple/src/Pimple/Container.php(118): {closure}(Object(Slim\Container))
#7 /Applications/MAMP/htdocs/auth/bootstrap/app.php(37): Pimple\Container->offsetG in /Applications/MAMP/htdocs/auth/vendor/illuminate/support/helpers.php on line 646

Does anyone know how to fix this?

**Comment by ingenuityon** [comment]
I found a work around... I was using the latest php 7.1.28, which constantly caused the issue above.  I downgraded php to 5.6.40 and re-installed and everything worked.  I noticed there was a mention of issues with 7.2, but the issue above seems to start at some point in the 7.1.x series

**Comment by rubensrocha** [comment]
Open composer.json go to this line `"vlucas/phpdotenv": "^2.3",` and change `2.3` to `3`

Run `composer update`

Open bootstrap/app.php and change this line

`$env = new Dotenv(__DIR__ . '/../');` 

to this one

`$env = Dotenv::create(__DIR__ . '/../');`

**Comment by devsavage** [comment]
Fixed
